### ISSUE TITLE
百度网盘打开里面是空的，没有权重文件

### ISSUE THREAD

**Issue by kr150** [Snowfallingplum/SHMT#2]
如题

**Comment by Snowfallingplum** [comment]
Please wait a moment, Baidu Cloud does not support uploading files over 4G. The weight files will be uploaded to Google Cloud tonight or tomorrow

**Comment by kr150** [comment]
> Please wait a moment, Baidu Cloud does not support uploading files over 4G. The weight files will be uploaded to Google Cloud tonight or tomorrow

Thank you for your quick recovery and for your open-source work
